### ISSUE TITLE
CommandLoadFailure: Problem loading gcloud.preview.app.get_resource_limits: No module named appengine.api. (For 1-hello-world)

### ISSUE THREAD

**Issue by zonito** [GoogleCloudPlatform/nodejs-getting-started#10]
```shell
--> gcloud preview app                                                                                            
Traceback (most recent call last):
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/gcloud/gcloud.py", line 194, in main
    _cli.Execute()
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/cli.py", line 534, in Execute
    args = self.__parser.parse_args(args)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 73, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 64, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 268, in __call__
    parser, namespace, values, option_string=option_string)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1111, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 64, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 268, in __call__
    parser, namespace, values, option_string=option_string)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1111, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 64, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<PATH>/google-cloud-sdk/././lib/argparse/__init__.py", line 1952, in _parse_known_args
    self.error(_('too few arguments'))
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 188, in error
    self._calliope_command, self._calliope_command.ai)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/usage_text.py", line 381, in ShortHelpText
    command.LoadAllSubElements()
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 978, in LoadAllSubElements
    element = self.LoadSubElement(name)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 1018, in LoadSubElement
    self.SubParser(), parent_group=self)
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 1070, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/calliope/backend.py", line 726, in _GetModuleFromPath
    module = imp.load_module(name, f, file_path, items)
  File "<PATH>/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/get_resource_limits.py", line 6, in <module>
    from googlecloudsdk.appengine.lib import appengine_client
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/appengine/lib/appengine_client.py", line 14, in <module>
    from googlecloudsdk.appengine.lib.external.api import appinfo
  File "<PATH>/google-cloud-sdk/././lib/googlecloudsdk/appengine/lib/external/api/appinfo.py", line 33, in <module>
    from google.appengine.api import pagespeedinfo
CommandLoadFailure: Problem loading gcloud.preview.app.get_resource_limits: No module named appengine.api.
```

Was following https://cloud.google.com/nodejs/getting-started/hello-world#download_app, and at the time of deployment - it fails.

Please guide.

Thanks

**Comment by zonito** [comment]
```yaml
Google Cloud SDK [0.9.69]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.9 (default, Feb  9 2015, 22:08:43)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]]
Site Packages: [Disabled]

Installation Root: [<PATH>/google-cloud-sdk]
Installed Components:
  core: [2015.07.10]
  app-engine-python: [1.9.23]
  core-nix: [2015.06.02]
  app-engine-python-extras: [1.9.21]
  gcutil-msg: [2015.07.02]
  app-engine-java: [1.9.23]
  gcloud: [2015.07.10]
  gsutil-nix: [4.12]
  bq-nix: [2.0.18]
  app-engine-php: [ ]
  beta: [2015.06.30]
  gsutil: [4.13]
  bq: [2.0.18]
  app-engine-php-darwin: [2015.07.10]
  alpha: [2015.06.30]
  preview: [2015.07.10]
  kubectl: []
  app: [2015.07.10]
  kubectl-darwin-x86_64: [0.20.2]
```

Some more information, in case you need

**Comment by jonparrott** [comment]
This could be due to an environment variable. Could you try running:

```
unset APPENGINE_RUNTIME
```

And retrying?

**Comment by zonito** [comment]
Thanks, It works! :)

**Comment by jonparrott** [comment]
Glad we could help.
