### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by jamesandersen** [GoogleCloudPlatform/nodejs-getting-started#25]
I hit the following snag upon trying to run the sample app locally before pushing to Google Cloud Platform.

```
├── google-auto-auth@0.2.2 (object-assign@3.0.0, google-auth-library@0.9.6)
└── gce-images@0.1.0 (object-assign@3.0.0, async@1.4.2, got@4.2.0, google-auto-auth@0.1.1)
um-macbook:2-structured-data jandersen$ npm start

> nodejs-getting-started@1.0.0 start /Users/jandersen/projects/2-structured-data
> node app.js

App listening at http://0.0.0.0:8080

/Users/jandersen/projects/2-structured-data/node_modules/gcloud/lib/common/util.js:448
  reqOpts.headers = reqOpts.headers || {};
                           ^
TypeError: Cannot read property 'headers' of undefined
    at Object.decorateRequest (/Users/jandersen/projects/2-structured-data/node_modules/gcloud/lib/common/util.js:448:28)
    at onAuthorized (/Users/jandersen/projects/2-structured-data/node_modules/gcloud/lib/common/util.js:356:32)
    at /Users/jandersen/projects/2-structured-data/node_modules/gcloud/node_modules/google-auto-auth/index.js:18:7
    at /Users/jandersen/projects/2-structured-data/node_modules/gcloud/node_modules/google-auto-auth/index.js:66:7
    at addScope (/Users/jandersen/projects/2-structured-data/node_modules/gcloud/node_modules/google-auto-auth/index.js:102:7)
    at callback (/Users/jandersen/projects/2-structured-data/node_modules/gcloud/node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/googleauth.js:41:5)
    at /Users/jandersen/projects/2-structured-data/node_modules/gcloud/node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/googleauth.js:124:9
    at process._tickCallback (node.js:415:13)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.22
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
npm ERR! nodejs-getting-started@1.0.0 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the nodejs-getting-started@1.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the nodejs-getting-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejs-getting-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jandersen/projects/2-structured-data/npm-debug.log
```

**Comment by jamesandersen** [comment]
Incidentally, just tried updating node to v4.1.2 and got the same stack trace

**Comment by jamesandersen** [comment]
For anyone else finding this... you may have forgotten the `gcloud init` step from [the walkthrough](https://cloud.google.com/nodejs/getting-started/using-cloud-datastore#before-you-begin) after installing the Google Cloud SDK.

:grimacing:

**Comment by jonparrott** [comment]
@stephenplusplus is there any way gcloud-node could give a better error message to users in this case?

**Comment by stephenplusplus** [comment]
Yeah, I'm not sure what went wrong here, but I'll try to reproduce.

**Comment by jonparrott** [comment]
Thanks. :)

**Comment by stephenplusplus** [comment]
I unfortunately haven't been able to reproduce this. @jamesandersen did this happen after going to "http://localhost:8080"? The stack trace doesn't take us back to any point in code that came from this app.

**Comment by jamesandersen** [comment]
Yep, didn't occur until after hitting http://localhost:8080/ and actually
it was after being redirected to `/books`.   I'd guess it was at that point
the first API call is made needing authorization.

**Comment by stephenplusplus** [comment]
Thanks! I reproduced, and will be sending a PR upstream to hopefully make this not as painful next time.

**Comment by jonparrott** [comment]
Thanks, @stephenplusplus :)
