### ISSUE TITLE
Auth error:Error: invalid_grant

### ISSUE THREAD

**Issue by valendesigns** [GoogleCloudPlatform/nodejs-getting-started#259]
I've cloned the repo, installed the dependencies, setup the GCP project, activated the Google+ API, initialized Datastore, added the bucket, created the OAuth client, and updated the `config.js` but when I run the app and go to `http://localhost:8080` I get `Auth error:Error: invalid_grant` in the terminal.

I can go to `http://localhost:8080/books/add` without any issues but when I try to add a book I get the follow error.
```
Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: invalid_grant
    at Object.exports.createStatusError (/Users/derek/WebstormProjects/node-demo/5-logging/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/derek/WebstormProjects/node-demo/5-logging/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/derek/WebstormProjects/node-demo/5-logging/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/derek/WebstormProjects/node-demo/5-logging/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/derek/WebstormProjects/node-demo/5-logging/node_modules/grpc/src/client_interceptors.js:845:24)
```

I can also authenticate with Google but when I logout the UI hangs and I have to reload the page. I'm not sure what I'm doing wrong. Could anyone help me troubleshoot by offering suggestions?

I'm running node v10.15.0 on OSX with WebStorm. I've tried both `4-auth` and `5-logging` and get the same error. I'm not sure if I need to do more setup for Datastore or activate another Google API but after many hours of trying to solve this on my own it's time to ask for help.

**Comment by fhinkel** [comment]
Thanks for opening an issue @valendesigns 👋 . 

Could you double check that the G+ API is enabled? I just ran the code from section 4 yesterday and it worked, but I was using an old project so I don't fully remember which extra steps I had to take. 

Also, what authorized redirect URLs did you set up in the [console](https://console.cloud.google.com/apis/credentials)? Mine look like this:
![screen shot 2019-01-25 at 1 37 29 pm](https://user-images.githubusercontent.com/101553/51765677-70c30600-20a6-11e9-92ad-813894b2743b.png)

**Comment by fhinkel** [comment]
Closing this due to inactivity. Let us know if we need to reopen it.
