### ISSUE TITLE
Error: no matching index found

### ISSUE THREAD

**Issue by aa505** [GoogleCloudPlatform/nodejs-getting-started#327]
nodejs-getting-started/2-structured-data

I keep getting the no matching index found (followed the instructions). Is there a step missing in the instructions to create the data ?

App listening on port 8080
Error: no matching index found.
    at Http2CallStream.<anonymous> (path/nodejs-getting-started/2-structured-data/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:205:15)
    at path/nodejs-getting-started/2-structured-data/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by fhinkel** [comment]
Hi @aa505 👋 Thanks for opening the issue. I'll have a look. Did you turn on Firestore in your project?

**Comment by aa505** [comment]
Yes, Firestore is turned on, and has data for some of the other projects that I was trying out.

> Hi @aa505 👋 Thanks for opening the issue. I'll have a look. Did you turn on Firestore in your project?

**Comment by TesslaRay** [comment]
I found the same problem in: nodejs-getting-started/3-binary-data.

>App listening on port 8080
Error: no matching index found.
    at Http2CallStream.<anonymous> (/Users/cristian/Documents/Development/web/nodejs-getting-started/3-binary-data/node_modules/google-gax/node_modules/@grpc/grpc-js/bu
ild/src/client.js:96:45)
    at Http2CallStream.emit (events.js:205:15)
    at /Users/cristian/Documents/Development/web/nodejs-getting-started/3-binary-data/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by dustingraham** [comment]
Just ran into this issue for /2-structured-data/

Error information is very obtuse. Following the bookshelf app tutorial. gcloud authed, git cloned, npm installed. Not many steps to get to this point. Although it seems like it could be related to trying other google cloud tools in the last day or two.
