### ISSUE TITLE
Error: ALREADY_EXISTS: Resource already exists in the project

### ISSUE THREAD

**Issue by gustavopradoreis** [GoogleCloudPlatform/nodejs-getting-started#351]
I'm getting this error, after the topic on pub/sub was created:

```
> nodejs-getting-started@1.0.0 start /app
> node ${SCRIPT:-app.js}

App listening on port 8080
/app/worker.js:59
      throw err;
      ^

Error: 6 ALREADY_EXISTS: Resource already exists in the project (resource=shared-worker-subscription).
    at Object.callErrorFromStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:75:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-getting-started@1.0.0 start: `node ${SCRIPT:-app.js}`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-getting-started@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-12T18_56_41_582Z-debug.log
```

I follow all the steps of this tutorial: https://cloud.google.com/nodejs/docs/tutorials/bookshelf-on-kubernetes-engine?hl=pt-br

**Comment by scottmcpherson** [comment]
I'm getting the same error on step 2 of **Deploying the Bookshelf backend** https://cloud.google.com/nodejs/docs/tutorials/bookshelf-on-kubernetes-engine

**Comment by JoaoVictorLacerda** [comment]
apparently this command creates a new topic, I believe you already have a topic created... Try using this code block:

```
const topicName = 'your-topic';
const messageId = await pubsub.topic(topicName).publish(Buffer.from("test"));
```

to see your topics, use:
```
const pubsub = new PubSub({projectId});
console.log( await pubsub.getTopics())
```

**Comment by hhovhann** [comment]
@JoaoVictorLacerda any equivalent for `pubsub-java` ?

```
const pubsub = new PubSub({projectId});
console.log( await pubsub.getTopics())
```

Otherwise if checking before creation via getTopic it failed with NO_FOUND, if not checks the second time that will failing with the ALREADY_EXISTS
