### ISSUE TITLE
Getting "(gcloud.app.deploy) Error Response: [13] An internal error occurred" while deploying my javascript app

### ISSUE THREAD

**Issue by kranti-rh** [GoogleCloudPlatform/nodejs-getting-started#593]
When I tried in debug mode, that's what I got:

Result: {
    "done": true,
    "error": {
        "code": 13,
        "message": "An internal error occurred."
    },
    "metadata": {
        "@type": "type.googleapis.com/google.appengine.v1.OperationMetadataV1",
        "endTime": "2023-04-27T08:29:16.999Z",
        "insertTime": "2023-04-27T08:14:15.374Z",
        "method": "google.appengine.v1.Versions.CreateVersion",
        "target": "apps/shadowbot-io-preprod/services/default/versions/20230427t134409",
        "user": "krprasad@redhat.com"
    },
    "name": "apps/shadowbot-io-preprod/operations/8c42bc15-7cb0-4b40-9d49-a9195f2618d3"
}
Updating service [default]...failed.                                                                                               
DEBUG: (gcloud.app.deploy) Error Response: [13] An internal error occurred.
Traceback (most recent call last):
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/krantiprasad/google-cloud-sdk/lib/surface/app/deploy.py", line 127, in Run
    return deploy_util.RunDeploy(
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 692, in RunDeploy
    deployer.Deploy(
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 471, in Deploy
    self.api_client.DeployService(new_version.service, new_version.id,
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 230, in DeployService
    return operations_util.WaitForOperation(
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/operations_util.py", line 307, in WaitForOperation
    completed_operation = waiter.WaitFor(
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 261, in WaitFor
    operation = PollUntilDone(
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 322, in PollUntilDone
    operation = retryer.RetryOnResult(
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 249, in RetryOnResult
    if not should_retry(result, state):
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 320, in _IsNotDone
    return not poller.IsDone(operation)
  File "/Users/krantiprasad/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/operations_util.py", line 182, in IsDone
    raise OperationError(requests.ExtractErrorMessage(
googlecloudsdk.api_lib.app.operations_util.OperationError: Error Response: [13] An internal error occurred.

**Comment by ee99ee** [comment]
Same

**Comment by jlopezxs** [comment]
Same here
